### ISSUE TITLE
Update to latest tactic version

### ISSUE THREAD

**Issue by listyque** [diegocortassa/docker-tactic#3]
I just wanted to check the latest version of tactic 5, but it looks like docker do not see versions of tactic above 4.8.
Any suggestions on how to get 5.0 or 4.9 of Tactic?

**Comment by diegocortassa** [comment]
Hey Alex, nice to ear from you! Hope you are well!

You are right, I neglected the tactic and tacticdev docker images!

I just merged pull request #4 which update the stable image to 4.9.1
and pull request  [#1](https://github.com/diegocortassa/docker-tacticdev/pull/1) which update the [dev version](https://github.com/diegocortassa/docker-tacticdev)  to 5.0.0.a01

You can pull the new images from docker hub:
diegocortassa/tactic for 4.9.1
diegocortassa/tacticdev for 5.0.0.a01
